- enterprise/v0.16/07_monitor/04_logs-to-s3.md
Porting over @ianstanton's [PR in /astronomer/docs ](https://github.com/astronomer/docs/pull/227) to this repo since we're planning on shipping these docs soon. Addresses astronomer/issues#1593
Notes:
- I changed the title to "Forward Astronomer Logs to Amazon S3"
- Menu = "Monitoring" (4th and last item) for _Enterprise Only_
- I cleaned up the format a bit and added some links to AWS docs that I thought would be helpful
In terms of content, @vparekh94 already approved this but I have two outstanding questions I want to make sure we address before we close out this PR:
1. What logs exactly are forwarded by default if you follow the guidelines in this doc? Is it Airflow task logs for all Airflow Deployments on the cluster, is it deployment-level logs (Webserver, Scheduler, Worker), or is …
> Add new Fluentd -> S3 doc #227

- cloud/stable/02_develop/04_cli-install-windows-10.md
> Fix minor typo

- enterprise/next/09_resources/01_release-notes.md
- enterprise/v0.16/09_resources/01_release-notes.md
@vishwas-astro @sjmiller609 I put together release notes for v0.16.5 and v0.16.4 as applicable only to Enterprise customers based on GH Issues + a few conversations with different devs about what change went where.
Lemme know if I'm wrong or missing anything or if you have any other more general feedback. Thank ya!
> LTS 0.16.4 and 0.16.5 release notes

- enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/next/08_troubleshoot/04_disaster-recovery.md
- enterprise/v0.16/08_troubleshoot/04_disaster-recovery.md
Hi all - Porting over the "Disaster Recovery" doc that @jpweber and I worked on last week ([currently lives here](https://docs.google.com/document/d/1yql16mGT4kQSfc8XCCm2IcSYNv-4rUPcVkw_EDlSXZ4/edit#heading=h.i89o82d8hghx)).
The plan was to keep this doc _private_ (e.g. as a Google Doc PDF) until it was entirely polished/customer-ready, as @jpweber also noted there are some gaps in our infra that are shown here (primarily that "our terraform creates a database and erroneously takes the cloud providers url for that database and plugs it right in to our platform").
With that said, I talked to @vishwas-astro and we agreed that we've polished up this doc enough from a copy/formatting perspective and already have a [Disaster Recovery doc](https://www.astronomer.io/docs/enterprise/v0.16/troubles …
> New Disaster Recovery Doc

- cloud/stable/06_resources/01_release-notes.md
- enterprise/next/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.12/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.13/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.14/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.15/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.16/06_manage-astronomer/02_manage-platform-users.md
@ashb Pointed out a broken link in this doc that referenced our old "Configure Permissions" doc which was not transferred over to this repo. File here: https://github.com/astronomer/docs-legacy-archived/blob/main/v0.16/ee-configuring-permissions.md
I went to fix the link and realized that we hadn't incorporated the content in that doc, so I:
- Added instructions on how to make and apply permission changes
- Reformatted some headers/hierarchy
> Rework Manage Users Doc

- enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.12/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.13/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.14/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
This PR addresses this GH Issue: https://github.com/astronomer/issues/issues/1633
I updated our existing "Upgrade Astronomer" doc ([lives here](https://www.astronomer.io/docs/enterprise/v0.16/manage-astronomer/upgrade-astronomer/)) with:
- An overview of our upgrade policy
- Explanation of platform versioning
- Instructions for patch upgrades, adopted from: https://github.com/astronomer/astronomer/tree/master/bin/migration-scripts#patch-version-updates
The README in the repo I linked above has a lot more info in terms of checking to make sure pod are up, instructions for minor upgrades etc. I wasn't sure what all to include but decided to start narrow to make sure we're clear/accurate and then add info as needed.
@sjmiller609 Since I believe you wrote up those instructions, can you give …
> Enterprise patch upgrade instructions

- enterprise/next/05_customize-airflow/06_integrate-iam.md
- enterprise/v0.16/05_customize-airflow/06_integrate-iam.md
Opening up a draft PR here to address @sjmiller609's feedback in this GitHub issue: https://github.com/astronomer/issues/issues/1587
The changes I made include:
- A new section that walks users through setting up IAM on Kubernetes prior to touching anything on Astronomer (with specific instructions/external docs links for EKS)
- Specify the need to set `serviceAccountAnnotationKey`
I mostly followed the Zendesk ticket here: https://astronomer.zendesk.com/agent/tickets/2262. It sounds like there are still a few outstanding questions relating to content I did not include:
- Do users need to pass the IAM role as an Airflow Connection to get all of this to work?
- Did we figure out why the role was being applied to some workers but not all?
- Does the role have to specify `"Action": …
> Enhance IAM Role Integration Doc

- cloud/stable/04_customize-airflow/06_airflow_api.md
- enterprise/next/05_customize-airflow/07_airflow-api.md
- enterprise/v0.16/05_customize-airflow/07_airflow-api.md
Wrote up Viraj's notes/doc on how to programmatically call the Airflow API using Astronomer service-account
Could use some review of "Overview" section. 
Added three docs - one to Enterprise -> Next folder, one to Enterprise -> 0.16 folder, one to Cloud. Edited all three to be specific to Enterprise vs Cloud as appropriate.
> Guide for calling Airflow API - astronomer/issues/#1813

- cloud/stable/03_deploy/06_ci-cd.md
- enterprise/next/04_deploy/06_ci-cd.md
- enterprise/v0.16/04_deploy/06_ci-cd.md
Added AWS CodeBuild to CICD doc and changed headers of example code/scripts so they are linkable (only H2 headers have built-in links)
> Added AWS CodeBuild to CICD doc /astronomer/issues/issues/1884

- enterprise/next/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.12/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.13/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.14/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.15/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.16/03_install/01_aws/02_install-aws-terraform.md
If Python 3 is installed but not available under the name `python3` I think these would fail, so just adding a note about that.
> fix: add note about python 3

- enterprise/v0.12/02_develop/03_kubepodoperator-local.md
- enterprise/v0.13/02_develop/03_kubepodoperator-local.md
- enterprise/v0.14/02_develop/03_kubepodoperator-local.md
- enterprise/v0.15/02_develop/03_kubepodoperator-local.md
- enterprise/v0.16/02_develop/03_kubepodoperator-local.md
The default .kube/config uses 'docker-desktop' as the cluster context instead of 'docker-for-dekstop'. Updating the example DAG to match so it works without any modifications
> Fixing small bug in example DAG on local KubernetesPodOperator doc

- cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
This PR refactors our existing Airflow Versioning doc to incorporate 0.22 changes to the user experience of upgrading Airflow versions. Resolves: https://github.com/astronomer/issues/issues/2109
@samblackk @vishwas-astro Feel free to take a look at this - still need to add screenshots and considering incorporating error scenarios.
> Refactored "Airflow Versioning" Doc

- ac/next/03_security.md
- ac/v1.10.10/01_get-started/03_security.md
- cloud/stable/01_get-started/01_quickstart.md
- cloud/stable/01_get-started/02_cloud-faq.md
- cloud/stable/02_develop/01_cli-quickstart.md
- cloud/stable/02_develop/02_customize-image.md
- cloud/stable/06_resources/01_release-notes.md
- enterprise/next/02_develop/01_cli-quickstart.md
- enterprise/next/02_develop/02_customize-image.md
- enterprise/next/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/next/09_resources/01_release-notes.md
- enterprise/next/09_resources/02_version-compatibility-reference.md
- enterprise/v0.12/02_develop/01_cli-quickstart.md
- enterprise/v0.12/02_develop/02_customize-image.md
- enterprise/v0.12/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.13/02_develop/01_cli-quickstart.md
- enterprise/v0.13/02_develop/02_customize-image.md
- enterprise/v0.13/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.14/02_develop/01_cli-quickstart.md
- enterprise/v0.14/02_develop/02_customize-image.md
- enterprise/v0.14/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.15/02_develop/01_cli-quickstart.md
- enterprise/v0.15/02_develop/02_customize-image.md
- enterprise/v0.15/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.16/02_develop/01_cli-quickstart.md
- enterprise/v0.16/02_develop/02_customize-image.md
- enterprise/v0.16/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.16/09_resources/01_release-notes.md
- enterprise/v0.16/09_resources/02_version-compatibility-reference.md
@ryanahamilton I changed the title and URL of this doc:
- `Airflow Versioning` > `Manage Airflow Versions`
- `/customize-airflow/airflow-versioning` > `/customize-airflow/manage-airflow-versions`
I changed a bunch of files so that our docs references don't require the redirect. Can you give it a quick glance to make sure I didn't miss anything obvious?
> Rename Airflow Versioning Doc + Replace doc references w/ new URL

- cloud/stable/06_resources/01_release-notes.md
- enterprise/next/09_resources/01_release-notes.md
- enterprise/v0.16/09_resources/01_release-notes.md
Basing these on this list: https://github.com/astronomer/issues/issues?page=3&q=is%3Aissue+milestone%3A0.22+is%3Aclosed
@vishwas-astro Could you take a look at these? 2 questions:
1. Should I include multiple scheduler support? I actually think it could be a nice teaser for Airflow 2.0
2. Looks like we actually pushed `v0.22.3` so I'll skip specifying those first 2 patches, let me know if you think otherwise
P.S. Let me make sure to add Enterprise v0.16.11 release notes - looks like they're not in here
> Astronomer Cloud v0.22 Release Notes

- cloud/stable/05_manage-astronomer/03_vpc-access.md
In January 2021, our infrastructure team plans to expand our Astronomer Cloud NAT gateway to support 4 Static IP addresses instead of 1 (https://github.com/astronomer/issues/issues/1871).
We have an existing ["VPC Access" doc](https://www.astronomer.io/docs/cloud/stable/manage-astronomer/vpc-access/) that needs to be updated to reflect this change. This PR:
- Instructs users to allowlist all 4 IP addresses
- Adds a note for existing customers that 3 of the IPs are new but need to be allow-listed by January 2021
- Removes the Ad-Hoc Query section from the doc since that page is deprecated from Airflow as a way to test DB connections
@jpweber Can you take a quick look at this and verify we're instructing users to do the right thing? Most of this doc is an example on AWS Redshift, but I'd …
> Edit Cloud VPC access Doc to add new IPs

- cloud/stable/06_resources/01_release-notes.md
Release notes include:
- Customer-visible issues in this milestone: https://github.com/astronomer/issues/issues?page=1&q=is%3Aissue+milestone%3A0.23+is%3Aclosed
- A note on Quay.io change
> Astronomer Cloud v0.23 Release Notes

- enterprise/next/09_resources/02_version-compatibility-reference.md
- enterprise/v0.16/09_resources/02_version-compatibility-reference.md
Capturing the changes we just discussed in Slack [here](https://astronomerteam.slack.com/archives/CJTN7S938/p1606843331142800).
TL;DR:
- Remove support for K8s 1.14 + 1.15 from 0.16.x
- Add support for K8s 1.18 to both 0.16.x + 0.23
Now, we officially only support 1.16, 1.17 and 1.18 across 0.16 + 0.23 (coming soon).
> Remove support for K8s 1.14 + 1.15 from Enterprise in Docs

- ac/README.md
- ac/next/01_local.md
- ac/v1.10.10/01_get-started/01_local.md
- cloud/README.md
- cloud/stable/01_get-started/01_quickstart.md
- cloud/stable/02_develop/01_cli-quickstart.md
- cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
- cloud/stable/05_manage-astronomer/02_houston-api.md
- cloud/stable/06_resources/01_release-notes.md
- enterprise/next/02_develop/01_cli-quickstart.md
- enterprise/next/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/next/06_manage-astronomer/04_houston-api.md
- enterprise/next/09_resources/01_release-notes.md
- enterprise/v0.12/02_develop/01_cli-quickstart.md
- enterprise/v0.12/06_manage-astronomer/04_houston-api.md
- enterprise/v0.12/09_resources/01_release-notes.md
- enterprise/v0.13/02_develop/01_cli-quickstart.md
- enterprise/v0.13/06_manage-astronomer/04_houston-api.md
- enterprise/v0.13/09_resources/01_release-notes.md
- enterprise/v0.15/02_develop/01_cli-quickstart.md
- enterprise/v0.15/06_manage-astronomer/04_houston-api.md
- enterprise/v0.15/09_resources/01_release-notes.md
- enterprise/v0.16/02_develop/01_cli-quickstart.md
- enterprise/v0.16/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.16/06_manage-astronomer/04_houston-api.md
- enterprise/v0.16/09_resources/01_release-notes.md
Closes https://github.com/astronomer/issues/issues/2296. Per discussion on Slack, agreement was reached that it's OK to refrain from hyphenation across all uses of open source. This is both how it's done in IBM's developer style guide, the AP style guide, and Google's open source documents.
> Replaced every instance of 'open-source' with 'open source'

- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
Fixed the following in HA postgresql example:
- Indentation
- `synchronousCommit` value needed quotes
- Removed metrics as it required additional values to be set
> Fix HA postgresql example in AKS guide

- .github/ISSUE_TEMPLATE/issue_template.md
Added a new issue template to be used for all doc issues going forward. This is the same one that was in the private repo, save for the updated label names.
> Issue template creation

- package.json
This is repo is a dependency of astronomer/astro-site. As depicted below it is one of three content dependencies, each with different package naming conventions. This will be one of a series of PRs to update to a common naming convention. I'll just be updating the package names, not the repo names.
New naming convention:
```json
"dependencies": {
"astro-guides": "astronomer/airflow-guides",
"astro-blog": "astronomer/astro-blog",
"astro-docs": "astronomer/docs",
}
```
> Use consistent naming convention across packages

- cloud/stable/04_customize-airflow/01_manage-airflow-versions.md
This PR simply adds AC 1.10.14 to the list of supported AC versions we have in ["Manage Airflow Versions."](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions)
> Add 1.10.14 to Supported AC Versions

- cloud/stable/03_deploy/02_deploy-cli.md
**NOTE: Review this pull request and merge it before reviewing this one, or else the screen shots will not appear: https://github.com/astronomer/web-assets/pull/11**
Because the Deploy Code guide uses slightly different screenshot naming conventions, I created new files and linked to those by updating the links in the main guide. This PR simply updates those links to point to the new screenshots.
> Updated screenshot hyperlinks to point to new screenshots

- cloud/stable/04_customize-airflow/06_airflow_api.md
- enterprise/next/05_customize-airflow/07_airflow-api.md
- enterprise/v0.16/05_customize-airflow/07_airflow-api.md
we omitted "/airflow/" from the url on two docs
> correcting the experimental api url

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.12/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.13/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.15/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
This includes both modified recommendations and general changes to wording for this content. The main change that hasn't yet been confirmed by SMEs is switching our references from "nodes" to "resources", which is consistent with Amazon's own wording on the site we link out to. 
When this PR is approved, I'll push the changes here to all other Enterprise versions.
> Updated our recommendations for node sizes in the AWS installation guide

- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
Closes https://github.com/astronomer/docs/issues/165. Looks like we accidentally linked to a local branch before, so updating these links to point towards the appropriate `-release` branches.
> Fixed broken links to example configurations

- cloud/stable/02_develop/02_customize-image.md
- cloud/stable/04_customize-airflow/02_manage-airflow-versions.md
@vparekh94 I drafted some guidelines to help users migration from Alpine to Debian, as Astronomer Certified no longer supports Alpine-based Docker images beginning with AC 1.10.14.
In this PR, I also:
- Renamed this doc from "Manage Airflow Versions" to "Upgrade Airflow"
- Moved headers/section titles up for a cleaner format
- Removed the description of Alpine v Debian to the new section on the topic to keep things simple to start
Can you give this a look and let me know what you think? This doc is generally a bit wordy/packed with information, but hoping it's easy to find/navigate for users nonetheless.
> Guidelines on Migration from Alpine to Debian

- linkchecker.yml
Fixes https://github.com/astronomer/issues/issues/2213#issuecomment-752254937
Created a GitHub action which checks our site for broken links every Sunday at 8am GMT. The results will appear in the `Actions` tab on GitHub.
> New cron job for checking broken links

- cloud/stable/02_develop/01_cli-quickstart.md
- enterprise/next/02_develop/01_cli-quickstart.md
- enterprise/v0.16/02_develop/01_cli-quickstart.md
This PR addresses the CLI Quickstart portion of this issue: https://app.zenhub.com/workspaces/documentation-5fcfce583ed44e0011db3db5/issues/astronomer/docs/179
It does _not_ address the long-term improvements we hope to make to our CLI guides, such as removing content that's redundant with the general CLI. The only new changes here are a slight reorganization from lettered to numbered steps in Step 3 and Step 4. Otherwise, this was a fairly straightforward port from Cloud to Enterprise. 
Once I receive written approval of the changes here, I'll push them to Enterprise v0.16 as well.
> Updated Cloud and Enterprise CLI quickstart guides

- enterprise/next/06_manage-astronomer/03_workspace-permissions.md
The *actual* last part to this PR: https://github.com/astronomer/docs/issues/179
Perhaps the most simple port yet. Only change was updating the doc title to say "Enterprise" instead of "Cloud". Currently going through our Cloud changelog to confirm that these changes can also be made to v0.16.
> 1:1 port from Cloud to Enterprise on Permissions doc

- enterprise/next/02_develop/02_customize-image.md
Final part of https://github.com/astronomer/docs/issues/179 !
The only differences I could find between the Cloud and Enterprise versions of these docs seems to come from this PR: https://github.com/astronomer/docs/pull/171/files
The only change I made was to update links and to remove the note stating that direct access to the Airflow CLI was an Enterprise-only feature. Once this change is approved, I'll push this back to v0.16 (or earlier, assuming the functionality is still supported.
> Moved Customizing Images changes from Cloud to Enterprise

- enterprise/next/05_customize-airflow/05_secrets-backend.md
Part 5 of https://github.com/astronomer/docs/issues/179
Most straightforward copy-over yet. Simply replaced the links that pointed to Cloud docs with their Enterprise equivalents. Otherwise, the docs are identical.
> Push Cloud changes to "Secrets Backend" doc to Enterprise

- enterprise/next/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.16/05_customize-airflow/01_manage-airflow-versions.md
Part 3 of this PR: https://app.zenhub.com/workspaces/documentation-5fcfce583ed44e0011db3db5/issues/astronomer/docs/179
There were very few Enterprise references to preserve. It seems to only be these two sections:
I'm not super familiar with managing Airflow versions, so @paolaperaza might have a better sense of anything else we need to take out for Enterprise in this doc. Once this change is approved, I'll push it back to v0.16.
> Push Cloud changes to "Manage Airflow Versions" doc to Enterprise

- cloud/stable/03_deploy/01_manage-workspaces.md
- enterprise/next/04_deploy/01_manage-workspaces.md
- enterprise/v0.16/04_deploy/01_manage-workspaces.md
Part 4 of this Issue: https://github.com/astronomer/docs/issues/179
While the Managing Workspaces doc has a long ways to go, this PR brings some of the vital fixes from the Cloud doc over to Enterprise. I also updated some references to Astronomer terms per our style guide across both Cloud and Enterprise versions.
The only new content here is a rewording of the last sentence in the Enterprise "Workspace Permissions" section.
> Ported Cloud version of the Manage Workspaces doc to Enterprise

- enterprise/next/01_get-started/01_quickstart.md
- enterprise/v0.16/01_get-started/01_quickstart.md
This PR synthesizes content from the Enterprise quickstart with improvements that were made to the Cloud quickstart guide last month. In general, the content hasn't changed - I updated the doc in the following ways:
- Reorganized steps to be more cohesive, as well as to follow a more natural pattern for installing certain features
- Linked to some new docs and improved wording to match our style guide
This update doesn't include screen shots from Airflow 2.0, but definitely can if we decide it's not disruptive to add those now.
> Updated Enterprise Quickstart with updates from Cloud quickstart

- enterprise/next/05_customize-airflow/04_airflow-alerts.md
Part 6 of https://github.com/astronomer/docs/issues/179
This PR takes the most recent changes from the Cloud version of our [Alerts](https://www.astronomer.io/docs/cloud/stable/customize-airflow/airflow-alerts) guide and ports them over to Enterprise. This one was also fairly straightforward, as the there's only a few changes after the big rewrite that weren't brought to Enterprise. 
Once this is approved, I'll bring the changes into v0.16.
> Cloud enterprise alerts

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
Submitting a PR here that instructs users to run a modified `$ helm install` command that assumes latest patch, such that they're not required to:
- Look up what the latest patch is in our release notes
- Specify that patch in `$ helm install`
I included instructions on how to specify a patch in this command if a user wants to override that. @sjmiller609 This is something you recently told me was possible, so I finally have it documented! Can you take a quick look at this?
The changes I made applies to install docs for all providers in v0.16, v0.23 and 'next'.
Related ProductBoard feedback: https://astronomer.productboard.com/feature-board/2193567-step-1-feature-backlog/features/6612989/detail
> Modify Enterprise Helm Install Command to Assume Latest Patch

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
This PR adds an openssl command to verify the order of domain, intermediate, root domains for the astronomer-tls secret.
> Add openssl command to verify order of certs

- cloud/stable/02_develop/01_cli-quickstart.md
- enterprise/next/02_develop/01_cli-quickstart.md
- enterprise/next/09_resources/03_version-compatibility-reference.md
- enterprise/v0.16/02_develop/01_cli-quickstart.md
- enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
- enterprise/v0.16/09_resources/03_version-compatibility-reference.md
- enterprise/v0.23/02_develop/01_cli-quickstart.md
- enterprise/v0.23/06_manage-astronomer/06_upgrade-to-0-23.md
- enterprise/v0.23/09_resources/03_version-compatibility-reference.md
This PR adds guidelines around Astronomer CLI and Platform versioning policy and recommendations, applicable to both Astronomer Cloud and Enterprise. Changes include:
1. Add CLI versions to Enterprise Versioning Compatibility Matrix
2. Add a step to our "Upgrade to Astronomer v0.23" guide that instructs users to upgrade the CLI
3. Add information around Platform <> CLI minor versioning in "CLI Quickstart"
Adding @jwitz as a reviewer here but @vishwas-astro @astrorfox feel free to take a look at this as well and provide feedback on any of the above. Once we're good with the changes here, I'll port them over to Cloud docs + v0.16/next Enterprise versions.
Related Astro CLI PR: https://github.com/astronomer/astro-cli/pull/339
Resolves: https://github.com/astronomer/docs/issues/162
> Add Astro CLI <> Platform Versioning guidelines to CLI Quickstart + Versioning Matrix

- enterprise/next/09_resources/03_version-compatibility-reference.md
- enterprise/v0.16/09_resources/03_version-compatibility-reference.md
- enterprise/v0.23/09_resources/03_version-compatibility-reference.md
Airflow 2.0 requires your Airflow Helm Chart version to be at least 0.18.6. Because we didn't have a version requirement before, there was no place to document this info.
To fix this, I've added a new version column to the `Astronomer Certified` table that indicates the minimum required version for Airflow Helm Charts. I'm torn whether to say `N/A` or `Any` for the AC versions where it doesn't matter, let me know what you think!
> Added a Helm Chart compatibility column to "Version Compatibility Reference"

- cloud/stable/03_deploy/01_manage-workspaces.md
- enterprise/next/04_deploy/01_manage-workspaces.md
- enterprise/v0.12/04_deploy/01_manage-workspaces.md
- enterprise/v0.13/04_deploy/01_manage-workspaces.md
- enterprise/v0.15/04_deploy/01_manage-workspaces.md
- enterprise/v0.16/04_deploy/01_manage-workspaces.md
- enterprise/v0.23/04_deploy/01_manage-workspaces.md
Resolves https://github.com/astronomer/docs/issues/182
For this guide renovation, I ended up going for a less extreme reimagining than what's proposed in the original issue. Instead, I  opted for a more simple overview of everything you can manage at the Workspace level with links to all relevant documentation. This significantly shortened the document.
Because each Workspace process is either super simple (changing Workspace name) or described in other docs, I organized this doc by menu items rather than processes. If this is approved, I'll push the changes to other Enterprise versions and Cloud (making sure to include Billing info for Cloud).
> Rewrote the Manage Workspaces doc to be more focused

- enterprise/next/06_manage-astronomer/09_renew-tls-cert.md
- enterprise/v0.16/06_manage-astronomer/09_renew-tls-cert.md
- enterprise/v0.23/06_manage-astronomer/10_renew-tls-cert.md
Closes https://github.com/astronomer/docs/issues/243
For step 3, the indentation was fully incorrect (both in the raw Markdown and on the site). For Step 4, it turned out that while our indented code in the raw Markdown was correct, the website was incorrectly rendering it due to the way I wrote the code fence in line with steps. This change should both keep the code in line with steps and properly indented.
> Fixed indentation in TLS guides

- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
We never added the `azure.enabled` value from our default `config.yaml` file in the Azure install guide. This PR adds that back to 0.23 and `next`, since those are the only versions people would still install.
> Added Azure config defaults into the Azure installation guide

- cloud/stable/01_get-started/02_cloud-faq.md
- cloud/stable/04_customize-airflow/06_airflow_api.md
- enterprise/next/05_customize-airflow/07_airflow-api.md
- enterprise/v0.23/05_customize-airflow/07_airflow-api.md
Resolves: https://github.com/astronomer/docs/issues/248
This PR does a few things:
- Adds information to our existing "Airflow API" doc around Airflow's new REST API
- Reformats headers slightly to match our new "Step" framework and format
Based on feedback from customers + internal folks, and a popular forum post: https://forum.astronomer.io/t/can-i-use-the-airflow-rest-api-to-externally-trigger-a-dag/162/14
> Add Guidelines on Requests to Airflow 2.0 REST API

- enterprise/next/06_manage-astronomer/01_integrate-auth-system.md
- enterprise/v0.23/06_manage-astronomer/01_integrate-auth-system.md
Closes https://github.com/astronomer/docs/issues/252
Simply added an `/` at the end of the Redirect URIs for both 0.23 and `next`. Also made the wording and formatting more clear so that it's easier to copy+paste the exact URI.
> Updated redirect links for Azure AD example

- enterprise/next/02_develop/02_customize-image.md
Resolves https://github.com/astronomer/docs/issues/217
Our example `Dockerfile.build` included lines that were specific to an Alpine-based image, even though the steps used a Debian-based image as an example. I've replaced these lines and included a note below the example file that explains what to do if you're using an Alpine-based image.
> Fixed Customize Image example using incorrect expression for Debian-based imaages

- .github/workflows/linkchecker.yml
Thanks to the work from @danielhoherd and the [Muffet](https://github.com/raviqqe/muffet/pull/154) team, we can now specify a rate limit for accessing links in our docs. This should result in less false flag 429 errors in our GH reports.
I referenced GitHub's docs to determine the rate limit. According to [this doc](https://docs.github.com/en/developers/apps/rate-limits-for-github-apps), the minimum rate limit for GH is 5,000 requests per hour (or about 1 request per second, which is the unit this flag uses).
> Updated link checker to limit 429 errors

- cloud/stable/02_develop/02_customize-image.md
- enterprise/next/02_develop/02_customize-image.md
- enterprise/next/09_resources/03_version-compatibility-reference.md
- enterprise/v0.15/02_develop/02_customize-image.md
- enterprise/v0.16/02_develop/02_customize-image.md
- enterprise/v0.16/09_resources/03_version-compatibility-reference.md
- enterprise/v0.23/02_develop/02_customize-image.md
- enterprise/v0.23/09_resources/03_version-compatibility-reference.md
Resolves https://github.com/astronomer/docs/issues/271.
Per a Slack discussion last week with @krisdock , it sounds like we don't properly support Python 3.8 yet for AC images (and Enterprise by extension, I assume?)
Because of that, I've removed Python 3.8 from our version compatibility chart. If this looks good, I'll add it to other docsets as well.
> Removed Python 3.8 from our compatibility charts

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
Closes https://github.com/astronomer/docs/issues/276
@rbankston Thought this note would be good to have in our installation guides, and I agree - it's not obvious that the secret file name has a strict convention. 
Follow-up Q: Will this apply to all installations, or just AWS? If it's universal, I'll push this same update to our GCP and AKS guides.
> Added a note about naming conventions for k8s secrets

- cloud/stable/03_deploy/06_ci-cd.md
- enterprise/next/04_deploy/06_ci-cd.md
- enterprise/v0.23/04_deploy/06_ci-cd.md
A user has pointed out that our build images referenced as ap-airflow is incorrect and should be ap-build. Without Docker installed in ap-airflow, it will not successfully build.
> Correct Build Image

- cloud/stable/03_deploy/06_ci-cd.md
- enterprise/next/04_deploy/06_ci-cd.md
- enterprise/v0.16/04_deploy/06_ci-cd.md
- enterprise/v0.23/04_deploy/06_ci-cd.md
@kentdanas Wrote some great info about CI/CD on Notion last week. I've done my best here to integrate that content with our existing CI/CD docs. While these guides still could use further improvement, I think this is a great first step. 
The most notable new content here is the inclusion of a high level `example setup` section. The new diagram visual and steps here help synthesize a reader's understanding of Airflow with Astronomer's functionality. 
There are also some changes to the GitHub Actions CI/CD script that should be reviewed in comparison to the script we had before. 
If these changes look good, I'll add this content to the Enterprise CI/CD doc as well. If there are any Enterprise-specific considerations for this content, let me know here @kentdanas
> Update CI/CD doc with high level overview and additional GitHub actions info

- cloud/stable/04_customize-airflow/01_upgrade-to-airflow-2.md
- cloud/stable/04_customize-airflow/02_manage-airflow-versions.md
- enterprise/next/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.23/05_customize-airflow/01_manage-airflow-versions.md
Airflow 1.10.15 is now available as an Astronomer Certified image compatible with the Astronomer Platform.
This PR:
- Adds 1.10.15 to the list of supported Airflow versions to our ["Upgrade Airflow" doc](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions) in Cloud, Enterprise `/next` and Enterprise `/v0.23` versions. 1.10.15 will not immediately be supported in v0.16.x, so I left it out from earlier doc versions.
- Removes `v` syntax when talking about Airflow versions (i.e. `v1.10.15`), since it's typically not used in the context of Airflow & AC
- Modifies instructions in ["Upgrade to Airflow 2.0" doc](https://www.astronomer.io/docs/cloud/stable/customize-airflow/upgrade-to-airflow-2) to encourage users to upgrade to 1.10.15 instead of 1.10.14
@jwitz …
> Add 1.10.15 to Supported AC versions + "Upgrade Airflow" Docs

- ac/next/04_deploy-dags.md
This guide is one of the key components of our "Getting started" series for Astronomer Core. Essentially, we want to provide some basic guidelines for deploying DAGs at production scale. 
I wanted to give a sense of how to do this without being overly prescriptive. To do that, I gave instructions for the essential actions you need to complete, but leave it up to the reader to implement any automation tools they might want to use going forward.
> Created a guide for deploying DAGs on Airflow using Astronomer Core

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
Closes https://github.com/astronomer/docs/issues/292#issuecomment-804077298
For 0.23.12, we need to describe how to configure various ingress annotations, as some of these are likely to be configured at installation. I have yet to add the example configuration for `service.beta.kubernetes.io/aws-load-balancer-type` as suggested by @rbankston because I still need clarity on these questions from the GH issue:
> @rbankston Is the example value you included something we expect all AWS customers to want by default? In the future we should have a full chart config guide, but I don't want to provide opinionated setup in a general installation guide.
>If this is something we want everyone to configure, is there an equivalent, generally-used value we can configure for GCP and AKS? If it's not …
> Added new Helm configuration to install guides

- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
Closes https://github.com/astronomer/docs/issues/293
Not sure when this got changed, but I think we can start establishing a writing best practice of suggesting specific names for components of the Astronomer system. It's easier to follow and create consistent instructions throughout our docs when things have specific names, especially when there's little reason for an organization to name these components anything other than what we suggest. 
In docs where the namespace is already assumed to be created, this could be a little more ambiguous, but for installation guides I agree that we should be consistent with naming to make an install as easy and clear as possible. 
If this looks good, I'll push it to the `v0.23` version of this doc as well.
> Clarified namespace creation command

- ac/next/install-docker.md
Closes https://github.com/astronomer/issues/issues/2766
This PR completes our V1 AC Install docset (coupled with https://github.com/astronomer/docs/pull/280). 
As with the previous doc, the goal here is less to get users familiar with AC and Airflow and more to provide a straightforward set of steps that can get a minimal Airflow environment running and ready to scale. Introductions to AC and Airflow will be handled in subsequent PRs.
> Install AC with Docker Compose

- cloud/stable/03_deploy/02_configure-deployment.md
- enterprise/v0.23/04_deploy/02_configure-deployment.md
Resolves https://github.com/astronomer/docs/issues/327.
We talk a lot about creating Deployments in docs, but never about deleting them. This simple PR adds information around deleting Deployments. I also added some Enterprise-specific information about deleting Deployments with custom release names, as we get a lot of questions about this and should have at least some cursory information about it in our docs.
> Added information about deleting Deployments

- ac/next/image.md
This is a starting draft for what is essentially an editorialized version of the Astronomer Core source code. The info here should provide additional context for various components of the software. When we don't have the exact info someone might be looking for, there should always be a link to the most relevant source code/ documentation. 
Most "controversial" call here was to not document the Astronomer FAB security manager. Based on this [Slack thread](https://astronomerteam.slack.com/archives/CGQSYG25V/p1613011191412100), it looks like the security manager isn't actually used in the open source image. It has to be configured, and that info is probably better suited in another document. 
Looking at other image docs online, there's some additional directions we can take with this. …
> Created a reference guide for AC's image architecture

- ac/next/install-dependencies.md
As part of our V1 AC Documentation Suite, this guide provides some options for installing both OS and Python-level dependencies on Airflow. 
Some interesting things to note in the guide, and some follow-up questions:
- Instead of documenting how to build a Python wheel ourselves, I linked out to the Airflow documentation describing that process. How do you feel about that link - should we be documenting that process ourselves?
-  I struggled between using "Dependencies" and "Packages" throughout the guide. Can these processes install anything other than packages? If not, then I will probably remove the word "dependencies" from the guide.
> Created a new guide for installing packages on AC

- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.25/03_install/03_azure/01_install-azure-standard.md
The default values in Azure installation document was confusing to the customers due to having many default values that needed to change. Also had `ssl` section of values.yaml in the wrong level.
> Fixing the Azure installation for typos and proper default values

- cloud/stable/02_develop/01_cli-quickstart.md
- enterprise/v0.23/02_develop/01_cli-quickstart.md
- enterprise/v0.25/02_develop/01_cli-quickstart.md
Resolves https://github.com/astronomer/docs/issues/239
Adapted the recommendation in the original GitHub issue. Made some changes based on the fact that we have a published the CLI reference guide. While I was in here, I also cleaned up some of the formatting across the rest of the quickstart.
> Added info on `astro dev kill` to CLI quickstarts

- cloud/stable/01_get-started/01_quickstart.md
- cloud/stable/02_develop/01_cli-quickstart.md
- enterprise/v0.25/01_get-started/01_quickstart.md
- enterprise/v0.25/02_develop/01_cli-quickstart.md
Resolves https://github.com/astronomer/docs/issues/347
Marc's latest [YouTube video](https://youtu.be/OihokE8u9D0) covers almost identical ground to our Cloud and CLI quickstarts, so I think it makes sense to offer it as an alternative to the written steps.
Just so there's not too much information at the beginning, I embedded it after the written quickstart as an h2 header. If people are looking for a video, they'll be able to see the title in the righthand side nav.
I also added this to the Enterprise quickstarts, although there's some differences between those guides and the video. For one, the `auth login` section of the video assumes the viewer is using Cloud. Also, unlike the quickstart, we don't cover accessing metrics in the video. Still I think they share enough in common that we …
> Embedded new YouTube video in quickstart guides

- enterprise/v0.23/09_resources/04_version-compatibility-reference.md
- enterprise/v0.25/09_resources/04_version-compatibility-reference.md
Our Astronomer Certified customers often request a more detailed version compatibility doc that specifies both Celery and Redis as Airflow components for folks who leverage the Celery Executor.
Creating a PR here that adds versions of Redis and Celery we support with all versions of AC. For context:
- Both the Celery and Redis providers are installed in our [AC Dockerfile under ARG SUBMODULES](https://github.com/astronomer/ap-airflow/blob/master/2.0.2/buster/Dockerfile#L112)
- To narrow in on the versions of each, I looked at Airflow's `setup.py` file here (filtered per version): https://github.com/apache/airflow/blob/2.0.2/setup.py
cc: @kaxil @ernest-kr Any chance either or both of you two could check me on versions here? Much appreesh 😊
> Add Celery and Redis to AC Version Compatibility Matrix

- .github/workflows/main.yml
We no longer have an `enterprise/next` folder, so the link checker started failing every time it ran. I looked into this more, and given that `check-modified-files-only` is set to yes we should be able to eliminate the `folder-path` parameter entirely.
As long as it's only looking at modified files, it should be fine that the [default behavior of the action](https://github.com/gaurav-nelson/github-action-markdown-link-check#configuration) is to check all folders in the repository. This will also decrease maintenance over time, as we wont have to add new Enterprise folder versions to the GH Action.
> Remove folder parameter from link checker

- cloud/stable/04_customize-airflow/01_upgrade-to-airflow-2.md
We were missing this step and so a customer will see errors when they try to deploy AC >= 2.0 with a backport-provider
> Add step to replace Backport Provider with Provider for 2.0

- cloud/stable/04_customize-airflow/02_manage-airflow-versions.md
- enterprise/v0.23/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.23/09_resources/04_version-compatibility-reference.md
- enterprise/v0.25/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.25/09_resources/04_version-compatibility-reference.md
Quick PR that adds AC 2.1 to our docs. AC 2.1 was released on Friday, May 21 and is available on both Cloud + Platform v0.23 + v0.25 today. This PR adds 2.1 to:
- Enterprise Version Compatibility Doc (v0.23 + v0.25)
- "Upgrade Apache Airflow" for both Cloud + Enterprise docs (v0.23 + v0.25)
@jwitz Can you give dis a quick look?
> Add AC 2.1 to Supported AC versions + "Upgrade Airflow" Docs

- enterprise/v0.25/02_develop/01_cli-quickstart.md
- enterprise/v0.25/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.25/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.25/03_install/03_azure/01_install-azure-standard.md
Resolves https://github.com/astronomer/docs/issues/376 (-ish, need to figure out an autogeneration solution).
I originally thought that keeping "example" CLI versions would be clear enough while also being easier to maintain across major versions, but at least three people now, including a customer, have mentioned it was confusing to see "v0.23" mentioned so often in a "v0.25" doc. We'll just need to maintain these versions like in other docs going forward (until we find a more sustainable solution).
> Changed example versions in the CLI Quickstart

- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.25/03_install/03_azure/01_install-azure-standard.md
From internal testing, it was found that single server Azure PostgreSQL breaks Astronomer. Only Flexible Server is supported.
> Update Azure Postgres requirement

- cloud/stable/03_deploy/05_environment-variables.md
- enterprise/v0.13/04_deploy/05_environment-variables.md
- enterprise/v0.15/04_deploy/05_environment-variables.md
- enterprise/v0.16/04_deploy/05_environment-variables.md
- enterprise/v0.23/04_deploy/05_environment-variables.md
- enterprise/v0.25/04_deploy/06_environment-variables.md
When adding environment variables into a .env file, the syntax is `KEY=VAR`. We accidentally said to use `ENV KEY=VAR`, which is the syntax for adding environment variables to a Dockerfile. 
When users follow the instructions as is, environment variables silently aren't loaded, which leaves a very confused customer :) We should consider adding a check to make sure that environment variables are properly formatted and that the key is uppercase in the future.
> fix example and instruction for setting variables in .env file

- cloud/stable/04_customize-airflow/07_airflow_api.md
- enterprise/v0.16/05_customize-airflow/07_airflow-api.md
- enterprise/v0.23/05_customize-airflow/08_airflow-api.md
- enterprise/v0.25/05_customize-airflow/08_airflow-api.md
Curly quotes cause syntax error. Replace with straight quotes
> Replace curly quotes in code blocks with straight quotes

- cloud/stable/06_resources/03_cli-reference.md
- enterprise/v0.15/09_resources/03_cli-reference.md
- enterprise/v0.16/09_resources/03_cli-reference.md
- enterprise/v0.23/09_resources/03_cli-reference.md
- enterprise/v0.25/09_resources/03_cli-reference.md
Minor changes to the `astro config` section of the CLI Reference Guide:
- Current documentation of the `astro config set` command is `astro config set <setting-name>:<value>`, however, the working command does not require a colon between the key and value
- Updated `astro config get` verbiage
- Updated the "Related documentation" link; throwing a 404 error when attempting to navigate via the existing link
> Updated astro config set command and related doc link

- enterprise/v0.16/07_monitor/03_platform-alerts.md
- enterprise/v0.23/07_monitor/03_platform-alerts.md
- enterprise/v0.25/07_monitor/03_platform-alerts.md
Resolves https://github.com/astronomer/docs/issues/387
Simple copy-paste job of Ralph's suggestion in the original issue. I like the idea of having "Certified" builds of some of these features that rival the functionality we have in Cloud, but between the Cloud beta heating up and the potential of the new docs site, I don't think now is a great time for me to work on this. These docs might need to look very different in a few months, and we can reapproach that idea then.
> Fixed Alertmanager configuration examples

- cloud/stable/05_manage-astronomer/01_workspace-permissions.md
- enterprise/v0.23/06_manage-astronomer/03_workspace-permissions.md
- enterprise/v0.25/06_manage-astronomer/03_workspace-permissions.md
Resolves https://github.com/astronomer/docs/issues/351
At some point in v0.23, we wrote that Deployment Viewers cannot view Airflow task logs, which are available in the Airflow UI. I tried to be more clear about what was / wasn't possible for this type of user. By saying "They can only", I avoid having to list out the many things that Deployment Viewers *can't* do.
It seems like we might have mistook task log access for Kibana logging metrics, but I don't think it's even necessary to mention that lack of permission here.
> Fixed Deployment Viewer permission information
