- enterprise/v0.16/06_manage-astronomer/01_integrate-auth-system.md
@vparekh94 Porting over your PR to our old docs repo here! I did some cleanup and added the local auth section you added there.
Can you give this a quick look and approve if you're good?
> Clean up auth doc, include viraj's PR from old repo

- ac/stable/02_production.md
- ac/v1.10.10/02_production.md
- enterprise/stable/08_troubleshoot/01_kubectl.md
- enterprise/stable/08_troubleshoot/03_debug-install.md
- enterprise/v0.12/08_troubleshoot/01_kubectl.md
- enterprise/v0.12/08_troubleshoot/03_debug-install.md
- enterprise/v0.13/08_troubleshoot/01_kubectl.md
- enterprise/v0.13/08_troubleshoot/03_debug-install.md
- enterprise/v0.14/08_troubleshoot/01_kubectl.md
- enterprise/v0.14/08_troubleshoot/03_debug-install.md
- enterprise/v0.15/08_troubleshoot/01_kubectl.md
- enterprise/v0.15/08_troubleshoot/03_debug-install.md
- enterprise/v0.16/08_troubleshoot/01_kubectl.md
- enterprise/v0.16/08_troubleshoot/03_debug-install.md
While looking at docs I found some http: links that could be https: links.
> Switch some links to use https

- cloud/stable/04_customize-airflow/05_secrets-backend.md
I am guessing we now have Syntax Highlighting so we can make this look better
> Add Syntax Highlighting to Secrets Backend Doc

- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
Just a quick update - seems like things have changed.
> Update Azure install guide

- cloud/stable/06_resources/01_release-notes.md
Starting a draft here for 0.19 Cloud release notes
> Cloud 0.19 release notes

- cloud/stable/02_develop/01_cli-quickstart.md
- enterprise/next/02_develop/01_cli-quickstart.md
- enterprise/v0.12/02_develop/01_cli-quickstart.md
- enterprise/v0.13/02_develop/01_cli-quickstart.md
- enterprise/v0.14/02_develop/01_cli-quickstart.md
- enterprise/v0.15/02_develop/01_cli-quickstart.md
- enterprise/v0.16/02_develop/01_cli-quickstart.md
> fix syntax typo

- cloud/stable/03_deploy/06_ci-cd.md
- enterprise/next/04_deploy/06_ci-cd.md
- enterprise/v0.12/04_deploy/06_ci-cd.md
- enterprise/v0.13/04_deploy/06_ci-cd.md
- enterprise/v0.14/04_deploy/06_ci-cd.md
- enterprise/v0.15/04_deploy/06_ci-cd.md
- enterprise/v0.16/04_deploy/06_ci-cd.md
Also updates some formatting consistency.
> Fix service account typos

- enterprise/v0.12/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.13/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.14/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.15/06_manage-astronomer/05_upgrade-astronomer.md
- package.json
Part of astronomer/issues#1750.
> Updates for repo name change

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
Hey @paolaperaza just made a change, thanks!
> AWS Install Guide fix - publicsignups astronomer/issues/#1759

- cloud/stable/02_develop/03_kubepodoperator-local.md
- cloud/stable/04_customize-airflow/03_kubepodoperator.md
- enterprise/next/02_develop/03_kubepodoperator-local.md
- enterprise/next/05_customize-airflow/03_kubepodoperator.md
- enterprise/v0.12/02_develop/03_kubepodoperator-local.md
- enterprise/v0.12/05_customize-airflow/03_kubepodoperator.md
- enterprise/v0.13/02_develop/03_kubepodoperator-local.md
- enterprise/v0.13/05_customize-airflow/03_kubepodoperator.md
- enterprise/v0.14/02_develop/03_kubepodoperator-local.md
- enterprise/v0.14/05_customize-airflow/03_kubepodoperator.md
- enterprise/v0.15/02_develop/03_kubepodoperator-local.md
- enterprise/v0.15/05_customize-airflow/03_kubepodoperator.md
- enterprise/v0.16/02_develop/03_kubepodoperator-local.md
- enterprise/v0.16/05_customize-airflow/03_kubepodoperator.md
https://astronomerteam.slack.com/archives/C015V2JFKT5/p1600181535010200
> Add missing comma in example

- enterprise/next/07_monitor/04_logs-to-s3.md
- enterprise/v0.16/07_monitor/04_logs-to-s3.md
> Fix typo in logs-to-s3

- enterprise/next/06_manage-astronomer/04_houston-api.md
- enterprise/v0.12/06_manage-astronomer/04_houston-api.md
- enterprise/v0.13/06_manage-astronomer/04_houston-api.md
- enterprise/v0.14/06_manage-astronomer/04_houston-api.md
- enterprise/v0.15/06_manage-astronomer/04_houston-api.md
- enterprise/v0.16/06_manage-astronomer/04_houston-api.md
Fixed all the documents with the typo.
> Houston API guide typo fix astronomer/issues/#1800

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
Made edits to Enterprise versions of AKS, GKE & EKS install guides, to note supported K8s versions, per https://astronomerteam.slack.com/archives/CLRKTKHGU/p1600380316013500?thread_ts=1597322012.142800&cid=CLRKTKHGU
> Kubernetes supported versions - astronomer/issues/#1785

- enterprise/next/reference/default.yaml
- enterprise/v0.12/reference/default.yaml
- enterprise/v0.13/reference/default.yaml
- enterprise/v0.14/reference/default.yaml
- enterprise/v0.15/reference/default.yaml
- enterprise/v0.16/reference/default.yaml
Add reference material from houston-api so we can take that repo private.
I am blocked on the automatic copying of code, but should have that worked out in a few days. This is just to unblock https://github.com/astronomer/issues/issues/824
> Manually copy houston-api/config/default.yaml for all documented versions

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
Added note to standard install guide as recommended in issue #1833.
> Add details around using non-Lets Encrypt certs in Standard Installation guides - Astronomer/issues/#1833

- enterprise/next/reference/authorization-handler.js
- enterprise/next/reference/update-deployment-index.js
- enterprise/v0.12/reference/authorization-handler.js
- enterprise/v0.13/reference/authorization-handler.js
- enterprise/v0.14/reference/authorization-handler.js
- enterprise/v0.15/reference/authorization-handler.js
- enterprise/v0.16/reference/authorization-handler.js
- enterprise/v0.16/reference/update-deployment-index.js
These files are referenced in docs, but I need to merge this change separately from the links so we have a permanent sha to link against, vs a sha that will be squashed or a branch name which will link to content that will change.
> Add some js files from houston-api

- cloud/stable/05_manage-astronomer/01_workspace-permissions.md
Target links away from /enterprise to /cloud, and use SHA vs branch name.
> Target links to files merged in last commit.

- cloud/stable/06_resources/01_release-notes.md
- enterprise/v0.16/09_resources/01_release-notes.md
Put together release notes for v0.20! Full list of GH issues here: https://github.com/astronomer/issues/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.20
@vishwas-astro Want to take a look? As of right now, I don't list support for AC 1.10.12.
> 0.20 release notes

- enterprise/next/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.16/03_install/01_aws/02_install-aws-terraform.md
Updated doc with suggested changes outlined in issue #1872
> Update Tf install Guide/updated preq versions/astronomer/issues/#1872

- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
Made an update to the steps in section 7 configure your Helm Chart in the GCP Standard Install guide. See issue #1894.
> GCP-install configure helm fix astronomer/issues/#1894

- cloud/stable/06_resources/01_release-notes.md
- enterprise/next/05_customize-airflow/01_airflow-versioning.md
- enterprise/next/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/next/09_resources/01_release-notes.md
- enterprise/v0.16/05_customize-airflow/01_airflow-versioning.md
- enterprise/v0.16/06_manage-astronomer/05_upgrade-astronomer.md
- enterprise/v0.16/09_resources/01_release-notes.md
@vishwas-astro Want to take a quick peek at this?
Based these on the following GH issues with the `0.16.9` label: https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.16.9+is%3Aclosed
> 0.16.9 Release Notes

- cloud/stable/06_resources/01_release-notes.md
Hey all, pushing up an initial commit for 0.21 Cloud release notes. Basing these changes off of this list: https://github.com/astronomer/issues/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.21
I'm not quite done yet with the "Status of Deploy" part - @ryanahamilton or @adam2k if either of you have an extra minute to look this over and add to it or correct what I already have in there I'd love feedback - particularly in helping articulate what this new feature will actually look like for users in the UI/CLI (even if the changes are minor).
@vishwas-astro Will plan to push this out as soon as 0.21 is live.
> v0.21 Cloud Release Notes

- cloud/stable/06_resources/01_release-notes.md
Based on: https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.21.1+is%3Aclosed
> Add cloud v0.21.1 release notes

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.12/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.12/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.12/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.13/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.13/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.13/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.14/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.14/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.14/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.15/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.15/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.15/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.16/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.16/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.16/03_install/03_azure/01_install-azure-standard.md
Fix typo in `docker login` examples.
> Fix arg: -p

- cloud/stable/05_manage-astronomer/01_workspace-permissions.md
This PR updates the `cloud/stable` docs for User permissions. Assets are already updated to `web-assets`. 
Please provide feedback to improve - this may just be a first pass.
> 0.22: Cloud - Deployment RBAC / Workspace RBAC 

- cloud/stable/01_get-started/01_quickstart.md
> Paola Example PR

- cloud/stable/02_develop/04_cli-install-windows-10.md
- enterprise/next/02_develop/02_customize-image.md
- enterprise/next/02_develop/04_cli-install-windows-10.md
- enterprise/next/06_manage-astronomer/04_houston-api.md
- enterprise/next/07_monitor/01_grafana-metrics.md
Resolves https://github.com/astronomer/issues/issues/2197
> Typo fixes

- cloud/stable/04_customize-airflow/05_secrets-backend.md
- enterprise/next/05_customize-airflow/05_secrets-backend.md
- enterprise/v0.12/05_customize-airflow/05_secrets-backend.md
- enterprise/v0.13/05_customize-airflow/05_secrets-backend.md
- enterprise/v0.14/05_customize-airflow/05_secrets-backend.md
- enterprise/v0.15/05_customize-airflow/05_secrets-backend.md
- enterprise/v0.16/05_customize-airflow/05_secrets-backend.md
Fix nested typos. Reported by @ben-astro 
https://astronomerteam.slack.com/archives/C015V2JFKT5/p1605797516038600
> Don't nest double-quotes, use single quotes instead.

- cloud/stable/06_resources/02_support.md
- enterprise/v0.12/08_troubleshoot/02_support.md
- enterprise/v0.13/08_troubleshoot/02_support.md
- enterprise/v0.15/08_troubleshoot/02_support.md
- enterprise/v0.16/08_troubleshoot/02_support.md
this matches what customers see in zendesk when opening a ticket
> update from s to p ratings on support pages

- cloud/stable/04_customize-airflow/04_airflow-alerts.md
- cloud/stable/06_resources/03_pricing.md
- enterprise/next/05_customize-airflow/04_airflow-alerts.md
- enterprise/v0.12/05_customize-airflow/04_airflow-alerts.md
- enterprise/v0.13/05_customize-airflow/04_airflow-alerts.md
- enterprise/v0.15/05_customize-airflow/04_airflow-alerts.md
- enterprise/v0.16/05_customize-airflow/04_airflow-alerts.md
Closes https://github.com/astronomer/issues/issues/2273. Some minor typo fixes in here as well.
> Fixed broken hyperlinks to h3-level topics.

- cloud/stable/05_manage-astronomer/02_houston-api.md
- enterprise/next/06_manage-astronomer/04_houston-api.md
- enterprise/v0.12/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.12/06_manage-astronomer/04_houston-api.md
- enterprise/v0.13/06_manage-astronomer/04_houston-api.md
- enterprise/v0.15/06_manage-astronomer/04_houston-api.md
- enterprise/v0.16/06_manage-astronomer/04_houston-api.md
Resolves astronomer/astro-site#194
I _think_ I got em all.
> Add/update GQL to code fence blocks

- cloud/README.md
- cloud/stable/01_get-started/01_quickstart.md
- enterprise/next/01_get-started/01_quickstart.md
This PR realigns our quickstart positioning to better fit our new customer onboarding process being pushed in our new website.
> Improve/update Cloud Quickstart

- ac/v1.10.10/01_get-started/03_security.md
- https://lists.apache.org/thread.html/rb3647269f07cc2775ca6568cbfd4994d862c842a58120d2aba9c658a%40%3Cusers.airflow.apache.org%3E
- https://lists.apache.org/thread.html/ree782a29d927b96bf0b39fb92e2f1f09ea3112a985f7a08ce93765ac%40%3Cusers.airflow.apache.org%3E
- https://lists.apache.org/thread.html/r4656959c8ed06c1f6202d89aa4e67b35ad7bdba5a666caff3fea888e%40%3Cusers.airflow.apache.org%3E
> Add Airflow CVEs published today

- cloud/stable/06_resources/02_support.md
- enterprise/next/09_resources/02_support.md
- enterprise/v0.12/09_resources/02_support.md
- enterprise/v0.13/09_resources/02_support.md
- enterprise/v0.15/09_resources/02_support.md
- enterprise/v0.16/09_resources/02_support.md
Updated priority level descriptions to align to support portal
> Align Priority Level Descriptions

- cloud/stable/01_get-started/01_quickstart.md
- cloud/stable/02_develop/01_cli-quickstart.md
Changes specific to the CLI guide.
> Revamp Cloud Quickstart + CLI Quickstart

- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- Add azure flag to helm config in installation guide
- This will only apply to LTS 0.23.x and onward
- Related to https://github.com/astronomer/issues/issues/2417
> Add azure flag to helm config

- enterprise/next/03_install/01_aws/02_install-aws-terraform.md
- enterprise/next/09_resources/03_version-compatibility-reference.md
- enterprise/v0.16/03_install/01_aws/02_install-aws-terraform.md
- enterprise/v0.16/09_resources/03_version-compatibility-reference.md
- Update AWS Terraform doc with changes specific to terraform 0.13
- Related to https://github.com/astronomer/issues/issues/1910
> Update docs for tf0.13 support astronomer/issues#1910

- enterprise/next/06_manage-astronomer/03_workspace-permissions.md
Missed a few final references to Cloud-specific features from the last PR on this issue: https://github.com/astronomer/docs/pull/193 - this PR catches those.
> Updated Enterprise version of Manage Workspaces doc

- enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
> Fix upgrade and rollback manifest url

- .spelling
- cloud/stable/03_deploy/06_ci-cd.md
- enterprise/next/04_deploy/06_ci-cd.md
- enterprise/v0.23/04_deploy/06_ci-cd.md
Add Azure DevOps code example to CI/CD documentation
> Add Azure DevOps Code Example Issue #2562

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
Closes https://github.com/astronomer/docs/issues/263
Quick and easy update from @rbankston.
> Added more nginx configs to EKS installation guides

- enterprise/next/04_deploy/06_ci-cd.md
- enterprise/v0.23/04_deploy/06_ci-cd.md
Closes https://github.com/astronomer/docs/issues/281
@prasadrayudu Wrote some great content about the prerequisite setup necessary for using Azure DevOps in CI/CD. While we should maintain an internal document for customer assistance, I updated our public docs with some links to Azure's documentation, as well as updated the skeleton `yaml` file to match what Rayudu had in his guide. 
Once this is approved, I'll push the same content to other versions of the doc.
> Added more prerequisites and info for using Azure DevOps CICD

- cloud/stable/06_resources/01_release-notes.md
- enterprise/next/09_resources/01_release-notes.md
- enterprise/v0.23/09_resources/01_release-notes.md
This PR only addresses the changelog component of our 0.23.12 docs. Additional changes to other docs will arrive in https://github.com/astronomer/docs/pull/299
I wrote small descriptions for the changes listed [here](https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.23.12+). If these look good, I'll additionally include them in our v0.23 docs.
> 0.23.12 Changelog

- enterprise/next/03_install/01_aws/01_install-aws-standard.md
- enterprise/next/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/next/03_install/03_azure/01_install-azure-standard.md
- enterprise/v0.23/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.23/03_install/02_gcp/01_install-gcp-standard.md
- enterprise/v0.23/03_install/03_azure/01_install-azure-standard.md
Same changes as in https://github.com/astronomer/docs/pull/304/ , but for other install guides as well.
> Applied changes from previous PR to other installs

- enterprise/next/06_manage-astronomer/01_integrate-auth-system.md
- enterprise/v0.23/06_manage-astronomer/01_integrate-auth-system.md
Resolves https://github.com/astronomer/docs/issues/264
Updated Ralph's original wording suggestion slightly based on my understanding of what an Okta tile is. If that's not right, let me know @rbankston 
Once this is approved, I'll push it to other doc versions.
> Added steps for configuring an Okta tile 

- cloud/stable/03_deploy/02_configure-deployment.md
- enterprise/v0.23/04_deploy/02_configure-deployment.md
I think the reason some bullet points were appearing as numbered steps is because they weren't indented enough. This PR should fix that.
> Fixed numbered bullet points in Configure Deployment Doc (hopefully)

- cloud/stable/05_manage-astronomer/02_houston-api.md
- enterprise/v0.23/06_manage-astronomer/04_houston-api.md
Resolves https://github.com/astronomer/docs/issues/102
Resolves https://github.com/astronomer/docs/issues/230
Resolves https://github.com/astronomer/docs/issues/330
Rounded up our existing Houston API issues into this PR. Example mutations came from PRs, forum posts, and slack discussions.
While I was in here, I tidied up some of the language in the other mutation examples. It wasn't comprehensive, but it should make these examples easier to read.
> Added 4 new Houston mutation examples to docs

- cloud/stable/04_customize-airflow/02_manage-airflow-versions.md
- enterprise/v0.16/09_resources/04_version-compatibility-reference.md
- enterprise/v0.23/05_customize-airflow/01_manage-airflow-versions.md
- enterprise/v0.23/09_resources/01_release-notes.md
- enterprise/v0.23/09_resources/04_version-compatibility-reference.md
This PR includes release notes for 0.23.14, as well as standard updates to version compatibility reference docs. 
I took a guess at what 2.0.2 changes were important to list here, let me know if there's something important that I should add!
> Updated release notes and image version reference docs for 0.23.14

- cloud/stable/02_develop/01_cli-quickstart.md
Fixing a broken link in the CLI quickstart.
> Broken link fix in CLI quickstart

- enterprise/v0.16/06_manage-astronomer/06_upgrade-to-0-23.md
- enterprise/v0.23/06_manage-astronomer/06_upgrade-to-0-23.md
- enterprise/v0.23/06_manage-astronomer/07_upgrade-to-0-25.md
- enterprise/v0.25/06_manage-astronomer/06_upgrade-to-0-25.md
- Switch from master to target version's release branch.
- Correct file locations for release 25.
Closes #354
> Improve release upgrade docs

- enterprise/v0.25/04_deploy/04_deploy-nfs.md
- enterprise/v0.25/09_resources/03_cli-reference.md
> More broken link hotfixes 

- ac/next/01_quickstart.md
- ac/next/03_security.md
- ac/next/install-docker.md
- ac/v1.10.10/01_get-started/03_security.md
- cloud/stable/06_astronomer-certified/02_ac-security.md
- enterprise/v0.16/09_resources/04_version-compatibility-reference.md
- enterprise/v0.23/08_astronomer-certified/05_ac-security.md
- enterprise/v0.23/10_resources/04_version-compatibility-reference.md
- enterprise/v0.25/10_resources/04_version-compatibility-reference.md
Fritz mentioned that the frontmatter of the Security docs had different capitalization from all other docs, which might be what's causing the sidenav to not load. 
Also fixed an egregious typo 🌞
> Potential security doc fix + typo hotfix

- enterprise/v0.25/03_install/01_aws/01_install-aws-standard.md
Closes https://github.com/astronomer/docs/issues/386
In addition to adding the ELB note, I corrected some places where we still refer to ELB as the default load balancer. Only updating the v0.25 version of this doc because it's for installation.
> Added a note about when to use ELB instead of NLB

- cloud/stable/05_manage-astronomer/01_workspace-permissions.md
- cloud/stable/05_manage-astronomer/02_houston-api.md
- enterprise/v0.25/06_manage-astronomer/02_manage-platform-users.md
- enterprise/v0.25/06_manage-astronomer/03_workspace-permissions.md
- enterprise/v0.25/06_manage-astronomer/04_houston-api.md
This PR includes non-release note doc updates for two changes coming with 0.25.3:
- Invite email bypasses
- Workspace Admin permission changes
The release notes for these changes are in https://github.com/astronomer/docs/pull/401
> Cloud + Enterprise 0.25.3 Documentation

- cloud/stable/07_resources/01_release-notes.md
- enterprise/v0.16/09_resources/04_version-compatibility-reference.md
- enterprise/v0.23/10_resources/04_version-compatibility-reference.md
- enterprise/v0.25/10_resources/01_release-notes.md
- enterprise/v0.25/10_resources/04_version-compatibility-reference.md
This is the PR for 0.25.3 release notes. Other documentation changes for 0.25.3 are in https://github.com/astronomer/docs/pull/400
When reviewing release notes, please check for the following:
- Have all noticeable changes been documented?
- Are the improvements/ bug fixes in the right category?
- Is there anything else we should showcase (e.g. anything more we can say about Kubernetes versioning)?
- Are there any changes that I missed when adding the release notes to our Cloud docs?
Also I can't remember/ find the source of this discussion, but did we agree to stop including the source PRs for changes in release notes? It looks like we didn't do that for v0.25.2.
> 0.25.3 Release Notes

- enterprise/v0.25/10_resources/01_release-notes.md
See https://github.com/astronomer/docs/pull/401#discussion_r661869020
> Release note hotfixes

- enterprise/v0.25/03_install/01_aws/01_install-aws-standard.md
- enterprise/v0.25/04_deploy/04_deploy-nfs.md
Resolves https://github.com/astronomer/docs/issues/388
Added a tiny note on using 2.0+ deployments, and also tidied up the language for the other considerations so that everything's in an active voice.
> Updated NFS Volume considerations
